### ISSUE TITLE
Flashing CarThing assertion error

### ISSUE THREAD

**Issue by Mizzmox** [BluDood/GlanceThing#3]
After getting my CarThing in burn mode, I attempted to run the following command, as in step 4 of flashing the CarThing:

python superbird_tool.py --restore_device C:\Users\jason\OneDrive\Documents\carthingstuff\DUMP

C:\Users\jason\OneDrive\Documents\carthingstuff\DUMP is the absolute path to my extracted image.
After running the command, I get the following output:

> Spotify Car Thing (superbird) toolkit, v0.1.6, by Thing Labs and Bishop Dynamics
>      https://github.com/thinglabsoss/superbird-tool   
>      Forked from https://github.com/bishopdynamics/superbird-tool
> 
> Found device booted in USB Burn Mode (ready for commands)
> restoring entire device from dumpfiles in C:\Users\jason\OneDrive\Documents\carthingstuff\DUMP
> initializing env subsystem
>  executing bulkcmd: "amlmmc env"
> Traceback (most recent call last):
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 236, in get_interface_and_endpoint
>     return self._ep_info[endpoint_address]
>            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
> KeyError: 129
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\jason\OneDrive\Documents\carthingstuff\superbird-tool\superbird_tool.py", line 340, in <module>
>     dev.send_env_file(f'{FOLDER_NAME}/env.txt')
>   File "C:\Users\jason\OneDrive\Documents\carthingstuff\superbird-tool\superbird_device.py", line 266, in send_env_file
>     self.send_env(env_data)
>   File "C:\Users\jason\OneDrive\Documents\carthingstuff\superbird-tool\superbird_device.py", line 256, in send_env
>     self.bulkcmd('amlmmc env')  # initialize env subsystem
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\OneDrive\Documents\carthingstuff\superbird-tool\superbird_device.py", line 214, in bulkcmd
>     resp = self.device.bulkCmd(command)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyamlboot\pyamlboot.py", line 590, in bulkCmd
>     return self.bulkCmdStat(timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyamlboot\pyamlboot.py", line 595, in bulkCmdStat
>     return self.dev.read(usb.util.ENDPOINT_IN | 1, BULK_REPLY_LEN,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 1021, in read
>     intf, ep = self._ctx.setup_request(self, endpoint)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 113, in wrapper
>     return f(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 228, in setup_request
>     intf, ep = self.get_interface_and_endpoint(device, endpoint_address)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 113, in wrapper
>     return f(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 238, in get_interface_and_endpoint
>     for intf in self.get_active_configuration(device):
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 113, in wrapper
>     return f(self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 252, in get_active_configuration
>     bConfigurationValue=self.backend.get_configuration(self.handle)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\jason\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\backend\libusb0.py", line 528, in get_configuration
>     assert ret == 1
>            ^^^^^^^^
> AssertionError

For reference, I'm using Windows 10, and I'm using Python 3.12.7 installed from the Microsoft store. I installed all the necessary packages the tutorial outlines using this python version. I hadn't run into any issues until now. 

I'm not sure how to interpret this error. I expected it to run without any issue as I followed the tutorial closely. I attempted running the command with a different cable connected to the CarThing, and got the same result. Insight is appreciated; unsure where to go from here.

**Comment by lukemarshburn** [comment]
The Superbird Github recommends using Python 3.10.x

**Comment by BluDood** [comment]
Hey! First you could try what Luke suggested, but if that doesn't work, could you perhaps try working in a folder outside OneDrive? That could perhaps be messing with something. Also, there are reports of Windows being a bit funky with superbird-tool, could you try Linux or even macOS if that's possible?

**Comment by BluDood** [comment]
Hey, I'll close this issue for now since there has been no activity for a week. Feel free to reopen it or contact me on Discord if you need more help :)

**Comment by suited-1** [comment]
using libusbk seems to have solved my issue!

**Comment by Pauly-gon** [comment]
> using libusbk seems to have solved my issue!

This also fixed my issue, thanks for suggesting it!

**Comment by TTTechnoPro** [comment]
Also fixed my issue, thanks again!
